Document: so-666
Title: Debian so-666 Manual
Author: <insert document author here>
Abstract: This manual describes what so-666 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/so-666/so-666.sgml.gz

Format: postscript
Files: /usr/share/doc/so-666/so-666.ps.gz

Format: text
Files: /usr/share/doc/so-666/so-666.text.gz

Format: HTML
Index: /usr/share/doc/so-666/html/index.html
Files: /usr/share/doc/so-666/html/*.html
